 
name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu-build-gcc-static:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.3
      with:
        cmake_args: -B./build;-DCMAKE_INSTALL_PREFIX:STRING=./artifacts/;-DCMAKE_C_COMPILER=gcc;-DCMAKE_CXX_COMPILER=g++;-DBUILD_SAMPLES=OFF;-DBUILD_TESTS=ON
        submodule_update: ON
    - name: Test-01
      run: ./build/Tests/Test01-Range
    - name: Test-02
      run: ./build/Tests/Test02-Distribution
    - name: Test-03
      run: ./build/Tests/Test03-DistributionFinder
    - name: Test-04
      run: ./build/Tests/Test04-FactorSetting
    - name: Test-05
      run: ./build/Tests/Test05-FactorConstruction
